name: output-codeql-db
description: Output the path of the CodeQL database
inputs:
  language:
    required: true
  codeql:
    required: false
outputs:
  path:
    value: ${{ steps.generate-codeql-database.outputs.path }}
runs:
  using: composite
  steps: 
    - id: generate-codeql-database
      shell: bash
      env:
        CODEQL_CLI: ${{ inputs.codeql || format('{0}/codeql', env.CODEQL_DIST) }}
        CODEQL_DB_DIR: ${{ runner.temp }}/codeql_databases/${{ inputs.language }}
        CODEQL_DB_NAME: codeql-${{ inputs.language }}-db.zip
      run: |
        set -o errexit
        set -o nounset
        test -d "$CODEQL_DB_DIR"
        $CODEQL_CLI database bundle --output "$CODEQL_DB_NAME" "$CODEQL_DB_DIR"
        echo "::set-output name=path::$CODEQL_DB_NAME"
