name: output-codeql-db
description: Output the path of the CodeQL database
inputs:
  language:
    required: true
outputs:
  path:
    value: ${{ steps.generate-codeql-database.outputs.path }}
runs:
  using: composite
  steps: 
    - id: generate-codeql-database
      shell: bash
      env:
        CODEQL_DB_DIR: ${{ runner.temp }}/codeql_databases/${{ inputs.language }}
      run: |
        set -o errexit
        set -o nounset
        test -d "$CODEQL_DB_DIR"
        zip \
          -9 \
          --verbose \
          --recurse-paths \
          "$RUNNER_TEMP/db.zip" \
          "$CODEQL_DB_DIR" \
          --exclude "$CODEQL_DB_DIR/log/*" \
          --exclude "$CODEQL_DB_DIR/results/*" \
          --exclude "$CODEQL_DB_DIR/working/*"
        echo "::set-output name=path::$RUNNER_TEMP/db.zip"
