name: output-codeql-db
description: Output the path of the CodeQL database
inputs:
  language:
    required: true
  codeql:
    required: false
outputs:
  path:
    value: ${{ steps.generate-codeql-database.outputs.path }}
runs:
  using: composite
  steps: 
    - id: generate-codeql-database
      shell: bash
      env:
        CODEQL_CLI: ${{ inputs.codeql || format('{0}/codeql', env.CODEQL_DIST) }}
        CODEQL_DB_DIR: ${{ format('{0}/codeql_databases/{1}', runner.temp, inputs.language) }}
      run: |
        $CODEQL_CLI database bundle --output database.zip "$CODEQL_DB_DIR"
        echo "::set-output name=path::$PWD/database.zip"
